# Generated by Django 5.0.4 on 2024-06-19 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_billing_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='billing_key',
        ),
        migrations.CreateModel(
            name='BillingKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_uid', models.CharField(max_length=255, unique=True)),
                ('imp_uid', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
