# Generated by Django 5.0.4 on 2024-04-24 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.TextField()),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('user_type', models.BooleanField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image_url', models.TextField()),
                ('min_bid_price', models.IntegerField()),
                ('max_bid_price', models.IntegerField()),
                ('bid_increment', models.IntegerField()),
                ('auction_start_time', models.DateTimeField()),
                ('auction_end_time', models.DateTimeField()),
                ('product_status', models.BooleanField()),
                ('present_max_bid_price', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.TextField()),
                ('size', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.user')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_result', models.BooleanField()),
                ('bid_price', models.IntegerField()),
                ('bid_time', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='products.product')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='products.user')),
            ],
            options={
                'db_table': 'bid',
            },
        ),
    ]
