# Generated by Django 5.0.4 on 2024-05-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_bid_bid_price_alter_bid_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.BooleanField(default=False),
        ),
    ]
