# Generated by Django 5.0.4 on 2024-05-31 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidder',
            old_name='bidder',
            new_name='bidder_id',
        ),
    ]
