# Generated by Django 5.0.4 on 2024-06-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_bidder_bidder_bidder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
