# Generated by Django 5.0.4 on 2024-06-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_bidder_bidder_bidder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='billing_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
