# Generated by Django 5.0.4 on 2024-06-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_bidder_billing_key'),
        ('products', '0008_alter_product_tags'),
    ]

    operations = [
    ]
