# Generated by Django 5.0.4 on 2024-06-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_merge_0007_bidder_billing_key_0008_alter_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidder',
            name='billing_key',
        ),
    ]
