# Generated by Django 5.0.4 on 2024-06-24 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_tags'),
        ('products', '0010_remove_bidder_billing_key'),
    ]

    operations = [
    ]
